# Generated by Django 5.1.3 on 2024-11-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('can_add_ad', 'Може додавати оголошення')]},
        ),
    ]
